String numberToText(int age) {
  String result;
  
    if (age = 1) {result = "one";}
    else if (age == 2) {result = "two";}
    else if (age == 3) {result = "three";}
    else if (age == 4) {result = "four";}
    else if (age == 5) {result = "five";}
    else if (age == 6) {result = "six";}
    else if (age == 7) {result = "seven";}
    else if (age == 8) {result = "eight";}
    else if (age == 9) {result = "nine";}
    else if (age == 10) {result = "ten";}
    else if (age == 11) {result = "eleven";}
    else if (age == 12) {result = "twelve";}
    else if (age == 13) {result = "thirteen";}
    else if (age == 14) {result = "fourteen";}
    else if (age == 15) {result = "fifteen";}
    else if (age == 16) {result = "sixteen";}
    else if (age == 17) {result = "seventeen";}
    else if (age == 18) {result = "eighteen";}
    else if (age == 19) {result = "nineteen";}
    else if (age == 20) {result = "twenty";}
    else if (age == 21) {result = "twenty-one";}
    else if (age == 22) {result = "twenty-two";}
    else if (age == 23) {result = "twenty-three";}
    else if (age == 24) {result = "twenty-four";}
    else if (age == 25) {result = "twenty-five";}
    else if (age == 26) {result = "twenty-six";}
    else if (age == 27) {result = "twenty-seven";}
    else if (age == 28) {result = "twenty-eight";}
    else if (age == 29) {result = "twenty-nine";}
    else if (age == 30) {result = "thirty";}
    else if (age == 31) {result = "thirty-one";}
    else if (age == 32) {result = "thirty-two";}
    else if (age == 33) {result = "thirty-three";}
    else if (age == 34) {result = "thirty-four";}
    else if (age == 35) {result = "thirty-five";}
    else if (age == 36) {result = "thirty-six";}
    else if (age == 37) {result = "thirty-seven";}
    else if (age == 38) {result = "thirty-eight";}
    else if (age == 39) {result = "thirty-nine";}
    else if (age == 40) {result = "forty";}
    else if (age == 41) {result = "forty-one";}
    else if (age == 42) {result = "forty-two";}
    else if (age == 43) {result = "forty-three";}
    else if (age == 44) {result = "forty-four";}
    else if (age == 45) {result = "forty-five";}
    else if (age == 46) {result = "forty-six";}
    else if (age == 47) {result = "forty-seven";}
    else if (age == 48) {result = "forty-eight";}
    else if (age == 49) {result = "forty-nine";}
    else if (age == 50) {result = "fifty";}
    else if (age == 51) {result = "fifty-one";}
    else if (age == 52) {result = "fifty-two";}
    else if (age == 53) {result = "fifty-three";}
    else if (age == 54) {result = "fifty-four";}
    else if (age == 55) {result = "fifty-five";}
    else if (age == 56) {result = "fifty-six";}
    else if (age == 57) {result = "fifty-seven";}
    else if (age == 58) {result = "fifty-eight";}
    else if (age == 59) {result = "fifty-nine";}
    else if (age == 60) {result = "sixty";}
    else if (age == 61) {result = "sixty-one";}
    else if (age == 62) {result = "sixty-two";}
    else if (age == 63) {result = "sixty-three";}
    else if (age == 64) {result = "sixty-four";}
    else if (age == 65) {result = "sixteen-five";}
    else if (age == 66) {result = "sixty-six";}
    else if (age == 67) {result = "sixty-seven";}
    else if (age == 68) {result = "sixty-eight";}
    else if (age == 69) {result = "sixty-nine";}
    else if (age == 70) {result = "seventy";}
  return result;
}
